export const REQUEST_TASKS = 'REQUEST_TASKS'
export const RECEIVED_TASKS = 'RECEIVED_TASKS'
export const REQUEST_TASK_DETAIL = 'REQUEST_TASK_DETAIL'
export const RECEIVED_TASK_DETAIL = 'RECEIVED_TASK_DETAIL'
export const REQUEST_UPDATE_TASK_DETAIL = 'REQUEST_UPDATE_TASK_DETAIL'
export const TASK_DETAIL_UPDATED = 'TASK_DETAIL_UPDATED'

export const REQUEST_PRIORITIES = 'REQUEST_PRIORITIES'
export const RECEIVED_PRIORITIES = 'RECEIVED_PRIORITIES'

export const TASK_REMOVED = 'TASK_REMOVED'
